"""
Django settings for netflixfake project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

#diretorio base que é a pasta onde o projeto esta no caso ProjetoNetFlixFake
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

#chave de segurança do projeto
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(8pzipi^hpc0&ir&oa$l(lpv4@@9_shun-q5ep3bim2s@(nge#'

#permite que as mudanças reflitam no projeto rodando
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

#apps instalados nesse caso todos que começa com django e padrão os
#os outros são os APPs criados filme...
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filme',
]

#processos do django de meio do caminho
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


#qual é o arquivo que esta a base de liks que comanda o site
ROOT_URLCONF = 'netflixfake.urls'


#onde fica os arquivos HTML templates
#e opções de contexto
#'DIRS': ['templates'], pega o templates que esta dentro do projeto nesse caso
#esses templates serve para o geral do site coisas padrão que vai influenciar em todas as paginas
#seria os templates mãe

#'APP_DIRS': True, aqui diz para o django procurar dentro do APP uma pasta templates que é especifico do app
#nesse caso tem o APP "filme" la dentro tem uma pasta templates que é espeficico desse APP
#nesse app os templates carrega coisas do template principal e pode ser alterado algumas coisas
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'filme.novos_context.lista_filmes_recentes',
                'filme.novos_context.lista_filmes_emalta',
                'filme.novos_context.filmes_destaque',
            ],
        },
    },
]


#onde esta o arquivo de configuração do servidor
WSGI_APPLICATION = 'netflixfake.wsgi.application'

#qual é banco de dados
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#validadores de senha que o django vai gerencias
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
#lingua do admnistrativo
#padrão LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'pt-br'
#qual é o fusohorario
#padrao TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Sao_Paulo'
#
USE_I18N = True

USE_TZ = True

#onde fica os arquivos Static
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

#variavel que diz onde esta a pasta STATIC
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

#configuração da pasta para usuario fazer upload
#nome da URL da imagem
MEDIA_URL = 'media/'
#variavel que diz onde esta a pasta MEDIA
MEDIA_ROOT = BASE_DIR / 'media'


#define as chaves primarias no bancos de dados
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
