# Generated by Django 6.0.5 on 2026-05-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
