# Generated by Django 6.0.5 on 2026-06-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_episodio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='data_criação',
            new_name='data_criacao',
        ),
    ]
